sudo: false
language: python
python: 3.5
services:
  - mysql
  - postgresql

env:
  global:
    - DATABASE_URL="postgres://postgres:@localhost/default"
    - SHARD_001_DATABASE_URL="mysql://travis:@localhost/shard_001"
    - SHARD_002_DATABASE_URL="postgres://postgres:@localhost/shard_002"
    - REPLICA_001_DATABASE_URL="postgres://postgres:@localhost/sharding_replica_001"
    - REPLICA_002_DATABASE_URL="postgres://postgres:@localhost/sharding_replica_002"
  matrix:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-djdev
    - TOX_ENV=py34-dj18
    - TOX_ENV=py34-dj19
    - TOX_ENV=py34-djdev
    - TOX_ENV=py35-dj18
    - TOX_ENV=py35-dj19
    - TOX_ENV=py35-djdev
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djdev
    - env: TOX_ENV=py34-djdev
    - env: TOX_ENV=py35-djdev

before_install:
  - psql -c 'DROP DATABASE IF EXISTS "default";' -U postgres
  - psql -c 'CREATE DATABASE "default";' -U postgres
  - mysql -e 'DROP DATABASE IF EXISTS shard_001;'
  - mysql -e 'CREATE DATABASE shard_001;'
  - psql -c 'DROP DATABASE IF EXISTS "shard_001";' -U postgres
  - psql -c 'CREATE DATABASE "shard_001";' -U postgres
  - psql -c 'DROP DATABASE IF EXISTS "sharding_replica_001";' -U postgres
  - psql -c 'CREATE DATABASE "sharding_replica_001";' -U postgres
  - psql -c 'DROP DATABASE IF EXISTS "sharding_replica_002";' -U postgres
  - psql -c 'CREATE DATABASE "sharding_replica_002";' -U postgres
install:
  - pip install --upgrade pip virtualenv tox coveralls --quiet
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
  - cat .tox/$TOX_ENV/log/*.log
